# Generated by Django 4.0.6 on 2022-07-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBackend', '0003_profile_email_alter_profile_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelQuote',
            fields=[
                ('quoteId', models.AutoField(primary_key=True, serialize=False)),
                ('gallonsRequested', models.IntegerField(default=0)),
                ('deliveryAddress', models.CharField(max_length=100)),
                ('deliverydate', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('AmountDue', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='userID',
            field=models.AutoField(default=1234, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
