# Generated by Django 4.0.6 on 2022-07-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBackend', '0005_remove_profile_password_fuelquote_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userID',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=11, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
