# Generated by Django 4.0.6 on 2022-07-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBackend', '0008_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
