name: Running Code Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2


    - name: Install dependencies
      run: pip install coverage
           pip install django

    - name: Run tests
      run: coverage run ./WebApp/manage.py test AppBackend -v 3 --force-color

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1